---
- name: checks for windows updates
  hosts: "{{ required_hosts }}"
  tasks:
  - name: Check for missing updates
    win_updates: state=searched
    register: update_count
  - name: available updates
    debug:
      var: update_count
