---
- name: changes the passwrod for the specified user
  hosts: "{{ required_hosts }}"
  vars_prompt:
    - name: username
      prompt: what user would you like to reset the password for?
      private: false
    - name: new_password
      prompt: what would you like the new users password to be?
      private: true
  tasks:
    - name: "Update password for {{ username }}"
      ansible.windows.win_user:
        name: "{{ username }}"
        password: "{{ new_password }}"
        state: present
