---
- name: creates the specified user
  hosts: "{{ required_hosts }}"
  vars_prompt:
    - name: new_user
      prompt: what would you like the new username to be?
      private: false
    - name: new_password
      prompt: what would you like the new users password to be?
      private: true
  tasks:
    - name: "Ensure user {{ new_user }} is present"
      ansible.windows.win_user:
        name: "{{ new_user }}"
        password: "{{ new_password }}"
        state: present
        groups:
          - Users
