---
- name: Enables the specified user
  hosts: "{{ required_hosts }}"
  vars_prompt:
    - name: username
      prompt: what user would you like to enable?
      private: false
  tasks:
    - name: "Ensure user account {{ username }} is enabled"
      ansible.windows.win_user:
        name: "{{ username }}"
        account_disabled: false
