---
- name: Removes account expiration for user
  hosts: "{{ required_hosts }}"
  vars_prompt:
    - name: new_user
      prompt: which user would you like to remove the account expiry from?
      private: false
  tasks:
    - name: Remove account expiration date
      ansible.windows.win_user:
        name: "{{ username }}"
        state: present
        account_expires: never
